#!/usr/bin/env python3
"""Generate src/data/offlineArtifacts.ts: which offline artifact exists for which locale.

The site must never link an artifact that is not there, and adding a language must not
require a code change. So this reads what is actually in public/ and emits a plain map.
The page components localize their copy through it: a locale whose own artifact exists
gets its own URL, and a locale without one keeps the default-locale URL rather than a 404.

Run it after rebuilding artifacts. It is a generated view, like conceptIndex.ts.
"""
import json
import os
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / 'tooling' / 'scripts'))
import content_paths  # noqa: E402

PUBLIC = REPO / 'public'
OUT = REPO / 'src' / 'data' / 'offlineArtifacts.ts'

with open(REPO / 'site.config.json', encoding='utf-8') as fh:
    SITE = json.load(fh)

DEFAULT = content_paths.DEFAULT_DIR
LOCALES = content_paths.LOCALES

# kind -> (filename for the default locale, filename for a locale code)
PATTERNS = {
    'epub': ('aied.epub', 'aied.{loc}.epub'),
    'pdf': ('aied.pdf', 'aied.{loc}.pdf'),
    'llms': ('llms.txt', 'llms.{loc}.txt'),
    'llmsConcepts': ('llms-concepts.txt', 'llms.{loc}-concepts.txt'),
    'llmsFull': ('llms-full.txt', 'llms.{loc}-full.txt'),
}


def main():
    manifest = {}
    for code in LOCALES:
        entry = {}
        for kind, (default_name, pattern) in PATTERNS.items():
            name = default_name if code == DEFAULT else pattern.format(loc=code)
            p = PUBLIC / name
            if p.is_file():
                entry[kind] = {
                    'url': f"{SITE.get('basePath', '/aied')}/{name}",
                    'bytes': p.stat().st_size,
                }
        if entry:
            manifest[code] = entry

    lines = [
        '// GENERATED by tooling/scripts/gen-offline-manifest.py - do not edit by hand.',
        '// Lists the offline artifacts that actually exist, per locale, so the site can',
        '// link a locale\'s own file and fall back to the default locale when it has none.',
        '',
        'export type OfflineArtifact = { url: string; bytes: number };',
        '',
        'export const offlineArtifacts: Record<string, Record<string, OfflineArtifact>> = '
        + json.dumps(manifest, indent=2, ensure_ascii=False)
        + ';',
        '',
        'export const defaultLocale = ' + json.dumps(DEFAULT) + ';',
        '',
    ]
    OUT.write_text('\n'.join(lines), encoding='utf-8')

    print(f"wrote {OUT.relative_to(REPO)}")
    for code, arts in manifest.items():
        detail = ', '.join(f"{k}={v['bytes']}" for k, v in arts.items())
        print(f"  {code}: {detail}")
    return 0


if __name__ == '__main__':
    sys.exit(main())