// GENERATED by tooling/scripts/gen-offline-manifest.py - do not edit by hand.
// Lists the offline artifacts that actually exist, per locale, so the site can
// link a locale's own file and fall back to the default locale when it has none.

export type OfflineArtifact = { url: string; bytes: number };

export const offlineArtifacts: Record<string, Record<string, OfflineArtifact>> = {
  "en": {
    "epub": {
      "url": "/aied/aied.epub",
      "bytes": 2476380
    },
    "pdf": {
      "url": "/aied/aied.pdf",
      "bytes": 6746456
    },
    "llms": {
      "url": "/aied/llms.txt",
      "bytes": 1104255
    },
    "llmsConcepts": {
      "url": "/aied/llms-concepts.txt",
      "bytes": 4826212
    },
    "llmsFull": {
      "url": "/aied/llms-full.txt",
      "bytes": 17314251
    }
  },
  "es": {
    "epub": {
      "url": "/aied/aied.es.epub",
      "bytes": 2764580
    },
    "pdf": {
      "url": "/aied/aied.es.pdf",
      "bytes": 7393294
    },
    "llms": {
      "url": "/aied/llms.es.txt",
      "bytes": 59350
    },
    "llmsConcepts": {
      "url": "/aied/llms.es-concepts.txt",
      "bytes": 5804824
    }
  },
  "fr": {
    "epub": {
      "url": "/aied/aied.fr.epub",
      "bytes": 2853300
    },
    "pdf": {
      "url": "/aied/aied.fr.pdf",
      "bytes": 7590512
    },
    "llms": {
      "url": "/aied/llms.fr.txt",
      "bytes": 52562
    },
    "llmsConcepts": {
      "url": "/aied/llms.fr-concepts.txt",
      "bytes": 6072489
    }
  },
  "zh": {
    "epub": {
      "url": "/aied/aied.zh.epub",
      "bytes": 2727154
    },
    "pdf": {
      "url": "/aied/aied.zh.pdf",
      "bytes": 7580414
    },
    "llms": {
      "url": "/aied/llms.zh.txt",
      "bytes": 153451
    },
    "llmsConcepts": {
      "url": "/aied/llms.zh-concepts.txt",
      "bytes": 4455603
    }
  },
  "de": {
    "epub": {
      "url": "/aied/aied.de.epub",
      "bytes": 2811765
    },
    "pdf": {
      "url": "/aied/aied.de.pdf",
      "bytes": 7456716
    },
    "llms": {
      "url": "/aied/llms.de.txt",
      "bytes": 59502
    },
    "llmsConcepts": {
      "url": "/aied/llms.de-concepts.txt",
      "bytes": 5513791
    }
  }
};

export const defaultLocale = "en";
