// GENERATED by tooling/scripts/gen-offline-manifest.py - do not edit by hand.
// Lists the offline artifacts that actually exist, per locale, so the site can
// link a locale's own file and fall back to the default locale when it has none.

export type OfflineArtifact = { url: string; bytes: number };

export const offlineArtifacts: Record<string, Record<string, OfflineArtifact>> = {
  "en": {
    "epub": {
      "url": "/aied/aied.epub",
      "bytes": 2476357
    },
    "pdf": {
      "url": "/aied/aied.pdf",
      "bytes": 6746378
    },
    "llms": {
      "url": "/aied/llms.txt",
      "bytes": 1104255
    },
    "llmsConcepts": {
      "url": "/aied/llms-concepts.txt",
      "bytes": 4826212
    },
    "llmsFull": {
      "url": "/aied/llms-full.txt",
      "bytes": 17314251
    }
  },
  "es": {
    "epub": {
      "url": "/aied/aied.es.epub",
      "bytes": 2754923
    },
    "pdf": {
      "url": "/aied/aied.es.pdf",
      "bytes": 7383408
    },
    "llms": {
      "url": "/aied/llms.es.txt",
      "bytes": 59350
    },
    "llmsConcepts": {
      "url": "/aied/llms.es-concepts.txt",
      "bytes": 5804824
    }
  },
  "fr": {
    "llms": {
      "url": "/aied/llms.fr.txt",
      "bytes": 9004
    },
    "llmsConcepts": {
      "url": "/aied/llms.fr-concepts.txt",
      "bytes": 732490
    }
  },
  "zh": {
    "epub": {
      "url": "/aied/aied.zh.epub",
      "bytes": 2697703
    },
    "pdf": {
      "url": "/aied/aied.zh.pdf",
      "bytes": 7546242
    },
    "llms": {
      "url": "/aied/llms.zh.txt",
      "bytes": 153451
    },
    "llmsConcepts": {
      "url": "/aied/llms.zh-concepts.txt",
      "bytes": 4455603
    }
  }
};

export const defaultLocale = "en";
