// GENERATED by tooling/scripts/gen-offline-manifest.py - do not edit by hand.
// Lists the offline artifacts that actually exist, per locale, so the site can
// link a locale's own file and fall back to the default locale when it has none.

export type OfflineArtifact = { url: string; bytes: number };

export const offlineArtifacts: Record<string, Record<string, OfflineArtifact>> = {
  "en": {
    "epub": {
      "url": "/aied/aied.epub",
      "bytes": 2182326
    },
    "pdf": {
      "url": "/aied/aied.pdf",
      "bytes": 5859894
    },
    "llms": {
      "url": "/aied/llms.txt",
      "bytes": 1001007
    },
    "llmsConcepts": {
      "url": "/aied/llms-concepts.txt",
      "bytes": 4338246
    },
    "llmsFull": {
      "url": "/aied/llms-full.txt",
      "bytes": 15343683
    }
  },
  "es": {
    "epub": {
      "url": "/aied/aied.es.epub",
      "bytes": 2419329
    },
    "pdf": {
      "url": "/aied/aied.es.pdf",
      "bytes": 6415975
    },
    "llms": {
      "url": "/aied/llms.es.txt",
      "bytes": 56978
    },
    "llmsConcepts": {
      "url": "/aied/llms.es-concepts.txt",
      "bytes": 5216799
    }
  }
};

export const defaultLocale = "en";
